#---- Setting
backend = "glx";
vsync = true;

#---- Blur
blur: {
  method = "dual_kawase";  # Найкращий та найшвидший метод
  strength = 2;           # Інтенсивність розмиття (від 1 до 20)
  deviation = 0.0;
  kernel = "";
};

blur-background = true;      
blur-background-frame = false;
blur-background-fixed = true;

#---- Corner
corner-radius = 10;

rounded-corners-exclude = [
    "class_g = 'dmenu'",
    "class_g = 'dwm'",
];

#---- Transparent
opacity-rule = [

  #---- Main software
  "75:class_g = 'obsidian'",
  "75:class_g = 'code-oss'",

  #---- Terminal
  "75:class_g = 'alacritty'",  

  #---- Suckless software
  "75:class_g = 'st-256color'",
  "75:class_g = 'dwm'",
  "75:class_g = 'dmenu'",
];

#---- Animations
fading = true;
fade-in-step = 0.01;     
fade-out-step = 0.01;   
fade-delta = 5;       

animations = true;

animation-stiffness = 180.0;
animation-dampening = 25.0;
animation-window-mass = 0.7;

animation-for-open-window = "zoom";
animation-for-unmap-window = "fade";
animation-for-transient-window = "fade";
animation-for-workspace-switch-in = "fade";
animation-for-workspace-switch-out = "fade";

